server:
  port: 10012
  max-http-header-size: 8192

spring:
  application:
    name: pf-outside

  cloud:
    nacos:
      discovery:
        server-addr: nacos.stalary.com
    sentinel:
      transport:
        port: 10003
        dashboard: sentinel.stalary.com

  zipkin:
    base-url: http://zipkin.stalary.com

  sleuth:
    sampler:
      probability: 1.0

  mail:
    host: smtp.163.com
    port: 465
    username: userscenter@163.com
    password: li1979101
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

logging:
  level:
    com.stalary.pf.outside.client: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
