server:
  port: 10000
  user: http://usercenter.stalary.com
  max-http-header-size: 8192

spring:
  application:
    name: pf-gateway
    apiVersion: v1
    
  cloud:
    nacos:
      discovery:
        server-addr: nacos.stalary.com

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: pf-user-v1
          uri: lb://pf-user
          predicates:
            - Path=/api/v1/user/**
          filters:
            - RewritePath=/api/v1/user(?<segment>/?.*), ${segment}

  zipkin:
    base-url: http://zipkin.stalary.com

  sleuth:
    sampler:
      probability: 1.0

logging:
  level:
    com.stalary.pf.gateway.client: DEBUG
    com.alibaba.nacos.client.naming: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
